{
  "formatVersion": "1.1",
  "component": {
    "group": "org.figuramc.fsb",
    "module": "fsb-fabric-any",
    "version": "0.6.1+fabric-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fsb-fabric-any-0.6.1+fabric-SNAPSHOT.jar",
          "url": "fsb-fabric-any-0.6.1+fabric-SNAPSHOT.jar",
          "size": 2064,
          "sha512": "1acfafed1a3c5e55c4b8b0df9e320f9242ab3c61da6bb514642f303307bc58698ad22e457d97a496ffe4dde31070912d3f77ab3d0a9c06ea1ed1b9465dcabc5b",
          "sha256": "7db5355bcbbfc5faf08b1d0b5f9d1c5e7e327ec1cf17ea0ba09426194328eacd",
          "sha1": "b147b7fef47f787162f8ed415a93b52cdd631e72",
          "md5": "fc88827a8c1e4b99c9c6f184a8b7eb59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-fabric-any-0.6.1+fabric-SNAPSHOT.jar",
          "url": "fsb-fabric-any-0.6.1+fabric-SNAPSHOT.jar",
          "size": 2064,
          "sha512": "1acfafed1a3c5e55c4b8b0df9e320f9242ab3c61da6bb514642f303307bc58698ad22e457d97a496ffe4dde31070912d3f77ab3d0a9c06ea1ed1b9465dcabc5b",
          "sha256": "7db5355bcbbfc5faf08b1d0b5f9d1c5e7e327ec1cf17ea0ba09426194328eacd",
          "sha1": "b147b7fef47f787162f8ed415a93b52cdd631e72",
          "md5": "fc88827a8c1e4b99c9c6f184a8b7eb59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-fabric-any-0.6.1+fabric-SNAPSHOT-sources.jar",
          "url": "fsb-fabric-any-0.6.1+fabric-SNAPSHOT-sources.jar",
          "size": 1700,
          "sha512": "5a7add3050aa3317f56b3ab62bdc6be9ce9392ca4798c40f3fb22e3e66154a5803f37bd2220dfbb126d2fa0bcfa8446c20714a46862b9522f12787714802e7f1",
          "sha256": "efc265d036b1719424e8bbec1b6f9ccaac7e2c8e26eed245d9b59f9b01634900",
          "sha1": "a921a2a549441b8edac3e38f46e4a02c5bdc2bb5",
          "md5": "797e9c49c82800b4b6749fd2397ac56e"
        }
      ]
    }
  ]
}
