{
  "formatVersion": "1.1",
  "component": {
    "group": "org.figuramc.fsb",
    "module": "fsb-api",
    "version": "0.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 55140,
          "sha512": "bc30b1423a906b83ecfdb852fe7faa4b9594d9433602a4eb93737ae9990faa8e77be3d3571a5415c187998b83dce7a9112c8b90f5b88714c2b9e5831f80dee23",
          "sha256": "95741fe66d96d49e43520aa01d94222a26d8b91d58c4aa46c5d6d525c9e35528",
          "sha1": "b74940e320b21826c0ac440801b7f8b5af6a6fee",
          "md5": "32c96ad06e06738dad2428f59009c4d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 55140,
          "sha512": "bc30b1423a906b83ecfdb852fe7faa4b9594d9433602a4eb93737ae9990faa8e77be3d3571a5415c187998b83dce7a9112c8b90f5b88714c2b9e5831f80dee23",
          "sha256": "95741fe66d96d49e43520aa01d94222a26d8b91d58c4aa46c5d6d525c9e35528",
          "sha1": "b74940e320b21826c0ac440801b7f8b5af6a6fee",
          "md5": "32c96ad06e06738dad2428f59009c4d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "size": 30391,
          "sha512": "259e8a8938a91b04b8a3aeac7ec403ed1660b69263d4dcdf6947581b3d778f3e71de6ceb944a606d4404cebb4de77d812f462e2f4945838778a90c93b7d5e4e8",
          "sha256": "a1ecff6748867ec57f31c05b5cb16843da7742b57fe75873d1bfe9d2595ea511",
          "sha1": "4e9015204d79556f424bab290f03580b6c198906",
          "md5": "e92b013094e1c22a927959716ac812a6"
        }
      ]
    }
  ]
}
