{
  "formatVersion": "1.1",
  "component": {
    "group": "org.figuramc.fsb",
    "module": "fsb-api",
    "version": "0.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 62338,
          "sha512": "5c693fc388a4947c46996b61c7bb74d687c6611a37bf30ca3bdd01977dd1e57ca2629afbefa80eb00c3610e4f42405dc62176cd557fcb431550532acd5479993",
          "sha256": "3de84c444a643c9076dbf3b79d8e4a2f6772089a08289ee93e4bdcfb994a93db",
          "sha1": "529d697c42ad4f5d2c23508be01a225de11ffb8d",
          "md5": "49a47bd339fa6c63488d3592adfecad5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 62338,
          "sha512": "5c693fc388a4947c46996b61c7bb74d687c6611a37bf30ca3bdd01977dd1e57ca2629afbefa80eb00c3610e4f42405dc62176cd557fcb431550532acd5479993",
          "sha256": "3de84c444a643c9076dbf3b79d8e4a2f6772089a08289ee93e4bdcfb994a93db",
          "sha1": "529d697c42ad4f5d2c23508be01a225de11ffb8d",
          "md5": "49a47bd339fa6c63488d3592adfecad5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "size": 31667,
          "sha512": "6ac3280f1fa244aed3edf2435eb4b492ce9ab3786417173e15a4dd7ca1474acf7b0252a290e4dd85feddd22bac5f3d2fc64e5864433a0269b6d7c1f4cb92f634",
          "sha256": "10af08efc0c5d993853b93cd1354126de3f6e50b96b14a384fa2cba346d0382a",
          "sha1": "cad8b2eea0e7f9fc005963835a7dbdbec341c49f",
          "md5": "baa61a396f4c1f2a9a5b1a51ed1e865a"
        }
      ]
    }
  ]
}
