{
  "formatVersion": "1.1",
  "component": {
    "group": "org.figuramc.fsb",
    "module": "fsb-api",
    "version": "0.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 55252,
          "sha512": "0859e880a1363ad2f7d0c2b4dfe9c8806291326f8e4958cc4abb147eb75d0e238e730f49c37e8ceb65d54222b4ba69be36f3e228d261425950ba41abefc57f88",
          "sha256": "520a564cba1cbc9e1ea5dcd93a69bf70b18cbd8f38a95912a854be9ccfdae4cb",
          "sha1": "9f580dc42e7b18d9c25257b4868430c6c44dfc4b",
          "md5": "7800585997a8843fcc77aed3f2e2346a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 55252,
          "sha512": "0859e880a1363ad2f7d0c2b4dfe9c8806291326f8e4958cc4abb147eb75d0e238e730f49c37e8ceb65d54222b4ba69be36f3e228d261425950ba41abefc57f88",
          "sha256": "520a564cba1cbc9e1ea5dcd93a69bf70b18cbd8f38a95912a854be9ccfdae4cb",
          "sha1": "9f580dc42e7b18d9c25257b4868430c6c44dfc4b",
          "md5": "7800585997a8843fcc77aed3f2e2346a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "size": 30424,
          "sha512": "d6fecaee6c2b2ee0da1c0d01f386365f11f3ed6b31f395a084a990ffe3b5e73cf7f26db148f91e16b9d970590a2d919a3086f0e6f16d94b27ed95f61484061e4",
          "sha256": "b1e9ae1b6054c02446bad482d17e0e7e97ff4696579322c538c122267a0e8f7a",
          "sha1": "311b098bc22db039a9f30700f5ac5c030900283b",
          "md5": "a809af877a471ad21be5378fdb06d663"
        }
      ]
    }
  ]
}
