{
  "formatVersion": "1.1",
  "component": {
    "group": "org.figuramc.fsb",
    "module": "fsb-api",
    "version": "0.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 55611,
          "sha512": "4a490f09cef4a3286dc1b649456458d55077e2025ecc3f56473be694b0a583b36db3ec5cabeb061685db8a9ac5d3aff04c25a46a26d8acacce7e72b7edcef1b2",
          "sha256": "940dd2dfb588d78894a43e7d50df2d137ccc68a7514e2f53ee65638d532492a8",
          "sha1": "88b55b552e9ab3de27c513913de96b6a2af18613",
          "md5": "c924e168e0c21f8502eee3a8a423f1e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 55611,
          "sha512": "4a490f09cef4a3286dc1b649456458d55077e2025ecc3f56473be694b0a583b36db3ec5cabeb061685db8a9ac5d3aff04c25a46a26d8acacce7e72b7edcef1b2",
          "sha256": "940dd2dfb588d78894a43e7d50df2d137ccc68a7514e2f53ee65638d532492a8",
          "sha1": "88b55b552e9ab3de27c513913de96b6a2af18613",
          "md5": "c924e168e0c21f8502eee3a8a423f1e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "size": 30597,
          "sha512": "a8af309e9def2431d6bb935eec61de3a2ae29c6dd9a5c7a08c6b51abf89cff2d1c0113ccf2ed9d3c7beb544f52a611d8764065a9a3035aa4f280b0c9dd4cede7",
          "sha256": "8f3d735b73a4316a6426b4b44c670b154f47002de5e87c00c3b1e0c857726213",
          "sha1": "a3841c1f97f75b0c4ddcfb2dd7ca9ef0460912d0",
          "md5": "adbace433960cdda4be8b02d7f59bdaf"
        }
      ]
    }
  ]
}
