{
  "formatVersion": "1.1",
  "component": {
    "group": "org.figuramc.fsb",
    "module": "fsb-api",
    "version": "0.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        }
      ],
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 62407,
          "sha512": "76fad9efb060c14d8f94e85e2cc9d351a7813c4529a9259e080893ea067b941ffae932f9a2e5a90b98f5fe546543438634fecbf6bf96a36988538a48218bd056",
          "sha256": "5e245167c8dc99a19d5fc4aa8ab59a9e1649949e4317ade5717b975aeac5a166",
          "sha1": "1f0aebfa6258bcbc07a88a902f634f2d57de5eab",
          "md5": "c0b020e4db0f235a683ce5bc1928d9f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT.jar",
          "size": 62407,
          "sha512": "76fad9efb060c14d8f94e85e2cc9d351a7813c4529a9259e080893ea067b941ffae932f9a2e5a90b98f5fe546543438634fecbf6bf96a36988538a48218bd056",
          "sha256": "5e245167c8dc99a19d5fc4aa8ab59a9e1649949e4317ade5717b975aeac5a166",
          "sha1": "1f0aebfa6258bcbc07a88a902f634f2d57de5eab",
          "md5": "c0b020e4db0f235a683ce5bc1928d9f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "url": "fsb-api-0.6.1-SNAPSHOT-sources.jar",
          "size": 31694,
          "sha512": "2d59c0c1c4e828bbe0e09f2ea568eabd4ce06da08bb0657d6af7a1e3febc4c8c6ac34255828afb6eb71cc9cc1444b21035383abd05348e8b7c3c21b813bed528",
          "sha256": "59a4f699b5e6c9a77dca8660934df6839c4bf27aa6cfcd447f99d6a4085fdd28",
          "sha1": "31a2075cfc8782cc8b1a32bc4d82ca16c370b387",
          "md5": "7081b0b9dfe60af44ab97153e04983be"
        }
      ]
    }
  ]
}
