{
  "formatVersion": "1.1",
  "component": {
    "group": "org.figuramc.fsb",
    "module": "fsb-server-api",
    "version": "0.6.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fsb-server-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-server-api-0.6.1-SNAPSHOT.jar",
          "size": 21923,
          "sha512": "dec42d22fcbec08e2b8cd8afe36ac01fc60f4abaa9c5a14ee72f2b4fde22fa1dbb008e33316f7b3d1fb95aa2663d9e718a2a461210113023b29190f273b5fdee",
          "sha256": "66b64e43397e71e2dc18deb3e64ea1a77da80310f048713d334a55b35d65259a",
          "sha1": "9d19a58cc946819c69148282b4bc9d0486b4be10",
          "md5": "e63b641cd30a1b600bf5b9780625344c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-server-api-0.6.1-SNAPSHOT.jar",
          "url": "fsb-server-api-0.6.1-SNAPSHOT.jar",
          "size": 21923,
          "sha512": "dec42d22fcbec08e2b8cd8afe36ac01fc60f4abaa9c5a14ee72f2b4fde22fa1dbb008e33316f7b3d1fb95aa2663d9e718a2a461210113023b29190f273b5fdee",
          "sha256": "66b64e43397e71e2dc18deb3e64ea1a77da80310f048713d334a55b35d65259a",
          "sha1": "9d19a58cc946819c69148282b4bc9d0486b4be10",
          "md5": "e63b641cd30a1b600bf5b9780625344c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fsb-server-api-0.6.1-SNAPSHOT-sources.jar",
          "url": "fsb-server-api-0.6.1-SNAPSHOT-sources.jar",
          "size": 11011,
          "sha512": "6017d1a45b361cb86ed85f0704984f5ef03c5c98837ac14330692cfbaa2c1fe104a89c6bbc2f631e41cf5d31a4dfd8f9a9c61012d10182f6ceaa9d1ddd736d60",
          "sha256": "56f5ac8388f136f4bd61341771efd1dd1a4d46c2b2377b5143216cf1e1987404",
          "sha1": "4b27f7ffea5ba148c19a4d8527df3350dff92cd7",
          "md5": "83d8108cae3e127ca0c64247e7af646f"
        }
      ]
    }
  ]
}
